sudo: required
services:
  - docker

before_install:
  - docker build -t agkhalil/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true agkhalil/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-770245323416"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
